#Config Server
spring:
  application:
    name: service-registry
  config:
    import: configserver:http://localhost:8888

#Local
#server:
#  port: 8761
#    
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false