server:
  servlet:
    context-path: /api/v1
  port: 8001
spring:
  application:
    name: authentication-service
security:
  jwt:
    secret-key: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    expiration-time: 3600000

baseuri:
  user: http://localhost:8101/api/v1/user/
  internal-user: http://localhost:8101/api/v1/internal/
  authentication: http://localhost:8001/api/v1/authenticate/
  
internal:
  auth:
    token: secret-token