server:
  servlet:
    context-path: /api/v1
  port: 8101
spring:
  application:
    name: user-service
  datasource:
      url: jdbc:postgresql://localhost:5432/USER_SERVICE
      username: postgres
      password: root
  jpa:
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

baseuri:
  user: http://localhost:8101/api/v1/user/
  authentication: http://localhost:8001/api/v1/authenticate/