server:
  servlet:
    context-path: /api/v1
  port: 8105
spring:
  application:
    name: order-matching-service
  datasource:
      url: jdbc:postgresql://localhost:5432/ORDER_MATCHING_SERVICE
      username: postgres
      password: root
  jpa:
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

baseuri:
  authentication: http://localhost:8001/api/v1/authenticate/
  user: http://localhost:8101/api/v1/user/
  stock: http://localhost:8102/api/v1/stocks/
  trading: http://localhost:8103/api/v1/trading/
  portfolio: http://localhost:8104/api/v1/portfolio/
  order-matching: http://localhost:8105/api/v1/order-matching/
  market-data: http://localhost:8106/api/v1/market-data/
  notification: http://localhost:8107/api/v1/notification/